services:
  lb:
    image: jaoppb/rinha-2026-lb:latest
    pull_policy: always
    restart: always
    volumes:
      - shared-data:/data/shared
    ports:
      - '9999:9999'
    environment:
      - UPSTREAMS=/data/shared/api1.sock,/data/shared/api2.sock
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '30M'

  api1: &api
    image: jaoppb/rinha-2026-rust:latest
    pull_policy: always
    restart: always
    volumes:
      - shared-data:/data/shared
    environment:
      - SOCK=/data/shared/api1.sock
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '160M'

  api2:
    <<: *api
    environment:
      - SOCK=/data/shared/api2.sock

volumes:
  shared-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: 'size=1m'
