FROM rust:1.85-slim AS builder

WORKDIR /app
COPY api/Cargo.toml api/Cargo.lock ./
# Create a dummy main.rs to build dependencies
RUN mkdir src && echo "fn main() {}" > src/main.rs && cargo build && rm -rf src

COPY api/src ./src
RUN cargo build && cp target/debug/api /api_bin

FROM debian:bookworm-slim
COPY --from=builder /api_bin /api
ENTRYPOINT ["/api"]
