services:
  lb:
    image: jaoppb/rinha-2026-lb:latest
    build: ./lb
    restart: always
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - shared-data:/data/shared
    ports:
      - '9999:9999'
    environment:
      - UPSTREAMS=/data/shared/api1.sock,/data/shared/api2.sock
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '30M'

  api1: &api
    image: jaoppb/rinha-2026-rust:latest
    build: .
    restart: always
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - shared-data:/data/shared
    environment:
      - SOCK=/data/shared/api1.sock
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '40M'

  api2:
    <<: *api
    environment:
      - SOCK=/data/shared/api2.sock

volumes:
  shared-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: 'size=1m'
